### ISSUE TITLE
pip install fails on FreeBSD (clang)

### ISSUE THREAD

**Issue by mike-pt** [torchbox/django-libsass#3]
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/local/lib/python2.7/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, _args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/local/lib/python2.7/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/local/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/libsass/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-sWz80n-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/libsass

**Comment by prydie** [comment]
We've come up against a similar issue previously with node-sass on FreeBSD. The easiest workaround is to install gcc and set `CC` when running `pip install -r requirements.txt`. Though I agree with @gasman that the issue should be fixed upstream.

**Example:**
```
CC=/usr/local/lib/gcc48 /home/vagrant/app/env/bin/pip install -r /home/vagrant/app/requirements.txt
```
